#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
# --env HTTP_SERVER_NAME="www.example.xyz" \
#     --env HTTPS_SERVER_NAME="www.example.xyz" \
#     --env SERVER_ADMIN="admin@example.xyz" \
#     --env TZ="Europe/Berlin" \
#     --env PHP_MEMORY_LIMIT="512M" \
#     --env UPLOAD_MAX_FILESIZE="8M" \
HOST = data.get('host')
SERVER_ADMIN = data.get('SERVER_ADMIN', 'admin@linkstack.org')
TZ = data.get('TZ', 'UTC')
PHP_MEMORY_LIMIT = data.get('PHP_MEMORY_LIMIT', '256M')
UPLOAD_MAX_FILESIZE = data.get('UPLOAD_MAX_FILESIZE', '8M')

linkstack = {
    'HTTP_SERVER_NAME': f'https://{HOST}',
    'HTTPS_SERVER_NAME': f'https://{HOST}',
    'SERVER_ADMIN': SERVER_ADMIN,
    'TZ': TZ,
    'PHP_MEMORY_LIMIT': PHP_MEMORY_LIMIT,
    'UPLOAD_MAX_FILESIZE': UPLOAD_MAX_FILESIZE
}
agent.write_envfile("linkstack.env", linkstack)
#agent.dump_env()
